name: validate-dotfiles
on: [push]
jobs:
  fish-syntax-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: fish-actions/install-fish@v1.1.0
      - run: fish -n fish/.config/fish/config.fish
